# Connascence Quality Gates Configuration
# This file defines configurable quality thresholds for connascence analysis
# Supports different project contexts, types, and adaptive thresholds

# Version of the configuration format
version: "1.0"

# Global default settings applied to all contexts unless overridden
defaults:
  # Enable/disable quality gates globally
  enabled: true
  
  # Fail analysis on threshold violations
  fail_on_violation: true
  
  # Include baseline comparison (requires previous analysis results)
  baseline_comparison: true
  
  # Reporting options
  reporting:
    detailed_violations: true
    summary_only: false
    export_metrics: true

# Context-specific configurations
# These apply based on file patterns and project areas
contexts:
  # Critical areas requiring stricter thresholds
  critical:
    # File patterns that match critical code areas
    patterns:
      - "src/auth/**"
      - "src/security/**" 
      - "src/payment/**"
      - "src/core/**"
      - "lib/critical/**"
      - "**/*security*"
      - "**/*auth*"
      - "**/*crypto*"
    
    # Stricter thresholds for critical areas
    thresholds:
      # NASA compliance thresholds (stricter for critical code)
      nasa_compliance:
        max_function_length: 40        # NASA: max 60 lines
        max_cyclomatic_complexity: 8   # NASA: max 10
        max_nesting_depth: 3          # NASA: max 4
        max_parameters: 4             # NASA: max 6
        
      # God object detection (very strict for critical areas)
      god_objects:
        max_methods: 15               # Standard: 20
        max_lines: 300               # Standard: 400
        max_responsibilities: 3       # Standard: 5
        
      # Duplication thresholds (zero tolerance in critical areas)
      duplication:
        max_duplicate_lines: 0        # No duplication allowed
        max_similar_blocks: 0         # No similar code blocks
        min_clone_length: 3          # Shorter clones detected
        
      # Connascence violation limits (very strict)
      violations:
        position: 0                  # No position connascence
        naming: 2                    # Very limited naming violations
        type: 1                      # Minimal type violations
        meaning: 0                   # No meaning violations
        algorithm: 0                 # No algorithm violations
        timing: 0                    # No timing violations
        execution: 0                 # No execution violations
        identity: 1                  # Minimal identity violations

  # Standard development areas with balanced thresholds  
  general:
    # File patterns for general application code
    patterns:
      - "src/**"
      - "lib/**"
      - "app/**"
      - "components/**"
      - "services/**"
      - "utils/**"
    
    # Balanced thresholds for general development
    thresholds:
      nasa_compliance:
        max_function_length: 60      # NASA standard
        max_cyclomatic_complexity: 10 # NASA standard  
        max_nesting_depth: 4         # NASA standard
        max_parameters: 6            # NASA standard
        
      god_objects:
        max_methods: 20              # Standard threshold
        max_lines: 400              # Standard threshold
        max_responsibilities: 5      # Standard threshold
        
      duplication:
        max_duplicate_lines: 10      # Allow minimal duplication
        max_similar_blocks: 3        # Allow some similar patterns
        min_clone_length: 6         # Standard clone detection
        
      violations:
        position: 3                 # Limited position violations
        naming: 5                   # Reasonable naming violations
        type: 3                     # Limited type violations  
        meaning: 2                  # Minimal meaning violations
        algorithm: 1                # Very limited algorithm violations
        timing: 1                   # Very limited timing violations
        execution: 1                # Very limited execution violations
        identity: 3                 # Limited identity violations

  # Test code with more relaxed thresholds
  testing:
    patterns:
      - "test/**"
      - "tests/**"
      - "spec/**"
      - "**/*.test.*"
      - "**/*.spec.*"
      - "__tests__/**"
    
    # More lenient thresholds for test code
    thresholds:
      nasa_compliance:
        max_function_length: 80      # Longer test functions allowed
        max_cyclomatic_complexity: 15 # Higher complexity for comprehensive tests
        max_nesting_depth: 5         # More nesting for test scenarios
        max_parameters: 8            # More parameters for test data
        
      god_objects:
        max_methods: 30              # Test suites can have many test methods
        max_lines: 600              # Longer test files allowed
        max_responsibilities: 8      # Test files can test multiple aspects
        
      duplication:
        max_duplicate_lines: 20      # Test setup duplication acceptable
        max_similar_blocks: 8        # Similar test patterns acceptable
        min_clone_length: 8         # Less sensitive clone detection
        
      violations:
        position: 8                 # Test data positioning less critical
        naming: 10                  # Descriptive test names may repeat
        type: 8                     # Test type variations acceptable
        meaning: 5                  # Test meaning patterns acceptable
        algorithm: 3                # Test algorithms can be similar
        timing: 5                   # Test timing less critical
        execution: 3                # Test execution patterns acceptable
        identity: 8                 # Test identity less critical

# Project-type specific configurations
# These override context settings based on project characteristics
project_types:
  # Security-critical projects (fintech, healthcare, defense)
  security_critical:
    # Enable this profile with: connascence --profile security-critical
    description: "Strictest thresholds for security-sensitive applications"
    
    # Override all context thresholds with security-first values
    global_overrides:
      nasa_compliance:
        max_function_length: 30      # Very short functions
        max_cyclomatic_complexity: 5  # Very low complexity
        max_nesting_depth: 2         # Minimal nesting
        max_parameters: 3            # Few parameters
        
      god_objects:
        max_methods: 10              # Very small classes
        max_lines: 200              # Very short files  
        max_responsibilities: 2      # Single responsibility focus
        
      duplication:
        max_duplicate_lines: 0       # Zero duplication tolerance
        max_similar_blocks: 0        # Zero similarity tolerance
        min_clone_length: 2         # Detect smallest clones
        
      violations:
        position: 0                 # No position violations
        naming: 1                   # Minimal naming violations
        type: 0                     # No type violations
        meaning: 0                  # No meaning violations
        algorithm: 0                # No algorithm violations
        timing: 0                   # No timing violations
        execution: 0                # No execution violations
        identity: 0                 # No identity violations

  # Performance-critical projects (real-time, high-throughput)
  performance_critical:
    description: "Optimized thresholds for performance-sensitive applications"
    
    global_overrides:
      nasa_compliance:
        max_function_length: 25      # Short functions for performance
        max_cyclomatic_complexity: 6  # Low complexity for predictability
        max_nesting_depth: 3         # Shallow nesting for performance
        max_parameters: 4            # Few parameters for call efficiency
        
      god_objects:
        max_methods: 12              # Small focused classes
        max_lines: 250              # Compact files
        max_responsibilities: 3      # Clear separation
        
      duplication:
        max_duplicate_lines: 0       # No duplication for maintainability
        max_similar_blocks: 1        # Minimal similarity
        min_clone_length: 4         # Detect performance-critical clones
        
      violations:
        position: 1                 # Minimal position coupling
        naming: 3                   # Limited naming coupling
        type: 2                     # Limited type coupling
        meaning: 1                  # Minimal meaning coupling
        algorithm: 2                # Some algorithm coupling for performance
        timing: 0                   # No timing coupling
        execution: 1                # Minimal execution coupling
        identity: 2                 # Limited identity coupling

  # Standard development projects
  standard:
    description: "Balanced thresholds for typical development projects"
    
    # Uses context-specific thresholds without global overrides
    use_context_thresholds: true

  # Prototype/experimental projects
  experimental:
    description: "Relaxed thresholds for rapid prototyping and experimentation"
    
    global_overrides:
      nasa_compliance:
        max_function_length: 100     # Longer functions acceptable
        max_cyclomatic_complexity: 20 # Higher complexity allowed
        max_nesting_depth: 6         # More nesting acceptable
        max_parameters: 10           # More parameters allowed
        
      god_objects:
        max_methods: 40              # Larger classes acceptable
        max_lines: 800              # Longer files acceptable
        max_responsibilities: 10     # Multiple responsibilities OK
        
      duplication:
        max_duplicate_lines: 50      # Significant duplication allowed
        max_similar_blocks: 15       # Many similar blocks allowed
        min_clone_length: 10        # Less sensitive detection
        
      violations:
        position: 15                # High position coupling allowed
        naming: 20                  # High naming coupling allowed
        type: 15                    # High type coupling allowed
        meaning: 10                 # Moderate meaning coupling allowed
        algorithm: 8                # Some algorithm coupling allowed
        timing: 5                   # Limited timing coupling
        execution: 8                # Some execution coupling allowed
        identity: 15                # High identity coupling allowed

# Monorepo configurations
# Special handling for multi-package repositories
monorepo:
  enabled: false  # Set to true for monorepo projects
  
  # Package-specific configurations
  packages:
    # Core/shared packages use stricter thresholds
    core_packages:
      patterns:
        - "packages/core/**"
        - "packages/shared/**"
        - "packages/common/**"
        - "libs/**"
      profile: "security_critical"  # Use security-critical profile
      
    # Application packages use standard thresholds  
    app_packages:
      patterns:
        - "packages/web-app/**"
        - "packages/mobile-app/**"
        - "apps/**"
      profile: "standard"  # Use standard profile
      
    # Tool/utility packages use relaxed thresholds
    tool_packages:
      patterns:
        - "packages/tools/**"
        - "packages/utils/**"
        - "tools/**"
      profile: "experimental"  # Use experimental profile

# Baseline comparison configuration
baseline:
  enabled: true
  
  # Baseline file location (relative to project root)
  file: ".connascence-baseline.json"
  
  # Comparison thresholds (percentage changes that trigger violations)
  thresholds:
    # Fail if violations increase by more than these percentages
    violation_increase:
      position: 10      # 10% increase in position violations fails
      naming: 15        # 15% increase in naming violations fails  
      type: 10          # 10% increase in type violations fails
      meaning: 5        # 5% increase in meaning violations fails
      algorithm: 0      # Any increase in algorithm violations fails
      timing: 0         # Any increase in timing violations fails
      execution: 0      # Any increase in execution violations fails
      identity: 10      # 10% increase in identity violations fails
      
    # Fail if god objects increase significantly
    god_object_increase: 20  # 20% increase in god objects fails
    
    # Fail if duplication increases significantly  
    duplication_increase: 25  # 25% increase in duplication fails

# Advanced configuration options
advanced:
  # File exclusion patterns (applied globally)
  exclude_patterns:
    - "node_modules/**"
    - "vendor/**"
    - "dist/**"
    - "build/**" 
    - "coverage/**"
    - "*.min.js"
    - "*.generated.*"
    
  # Language-specific configurations
  languages:
    javascript:
      # JavaScript-specific threshold adjustments
      threshold_multipliers:
        nasa_compliance:
          max_function_length: 1.2   # 20% more lenient for JS
        god_objects:
          max_methods: 0.8          # 20% stricter for JS classes
          
    python:
      # Python-specific threshold adjustments  
      threshold_multipliers:
        nasa_compliance:
          max_function_length: 0.8   # 20% stricter for Python
        god_objects:
          max_lines: 1.5            # 50% more lenient for Python classes
          
    java:
      # Java-specific threshold adjustments
      threshold_multipliers:
        god_objects:
          max_methods: 1.3          # 30% more lenient for Java
        violations:
          type: 0.7                 # 30% stricter for type violations
          
    csharp:
      # C#-specific threshold adjustments
      threshold_multipliers:
        nasa_compliance:
          max_parameters: 1.2       # 20% more lenient for C# methods
        violations:
          naming: 0.8               # 20% stricter for naming violations

# Integration settings
integration:
  # CI/CD integration options
  ci_cd:
    # Return non-zero exit code on violations
    fail_build_on_violation: true
    
    # Generate reports for CI systems
    generate_reports: true
    
    # Report formats to generate
    report_formats:
      - "json"      # Machine-readable JSON
      - "junit"     # JUnit XML for CI integration
      - "console"   # Human-readable console output
      - "markdown"  # Markdown summary for PR comments
      
  # IDE integration options
  ide:
    # Generate IDE-compatible warning files
    generate_warnings: true
    
    # Warning file formats
    warning_formats:
      - "vscode"    # VS Code problems format
      - "intellij"  # IntelliJ inspection format
      - "eslint"    # ESLint-compatible format

# Notification settings
notifications:
  # Webhook notifications on quality gate violations
  webhooks:
    enabled: false
    url: ""  # Set webhook URL
    
  # Email notifications  
  email:
    enabled: false
    recipients: []  # List of email addresses
    
  # Slack notifications
  slack:
    enabled: false
    webhook_url: ""  # Slack webhook URL
    channel: "#quality-gates"

# Custom rule definitions
# Define custom connascence detection rules
custom_rules:
  # Example: Custom naming pattern detection
  strict_naming_convention:
    enabled: false
    description: "Enforce strict naming conventions"
    pattern: "^[a-z][a-zA-Z0-9]*$"  # camelCase only
    applies_to: ["variables", "functions"]
    
  # Example: Custom position coupling detection
  parameter_order_consistency:
    enabled: false
    description: "Detect inconsistent parameter ordering"
    min_occurrences: 3  # Flag if same function called 3+ times with different orders
    
  # Example: Custom meaning coupling detection  
  magic_number_detection:
    enabled: true
    description: "Detect magic numbers indicating meaning coupling"
    exclude_values: [0, 1, -1, 2]  # Common acceptable magic numbers
    min_occurrences: 2  # Flag numbers used 2+ times