"""
Constants Package - Centralized Magic Literal Definitions
==========================================================

This package contains extracted magic literals organized by source module.
All magic literals have been extracted to improve code maintainability.

Usage:
    from analyzer.constants.master_constants import (
        SEVERITY, DESCRIPTION, TYPE, MAX_FUNCTION_LINES
    )

    from analyzer.constants.unified_analyzer_constants import (
        BUFFER_SIZE, CORRELATIONS
    )

Modules:
    master_constants: Common constants used across multiple modules
    *_constants: Module-specific constants

Auto-generated by: scripts/extract_magic_literals.py
"""

# Re-export master constants for convenience
try:
    from .master_constants import *
except ImportError:
    pass  # Master constants not yet created

__all__ = [
    # Will be populated with actual constant names
]
