# Tier-C Autofix Demonstration: Magic Literal Extraction
# Repository: Example public repository (https://github.com/example/demo-connascence)
# This demonstrates a working autofix that compiles and passes tests

# BEFORE: Connascence of Meaning violations (magic literals)
class DatabaseConnection:
    def __init__(self, host, port=5432):
        self.host = host
        self.port = port
        self.timeout = 30  # Magic literal - violation!
        self.max_retries = 3  # Magic literal - violation!
        self.buffer_size = 8192  # Magic literal - violation!
    
    def connect(self):
        # Magic literals in conditional logic
        if self.timeout > 60:  # Magic literal - violation!
            raise ValueError("Timeout too large")
        
        if self.max_retries > 10:  # Magic literal - violation!  
            raise ValueError("Too many retries")
    
    def read_data(self, chunk_size=1024):  # Magic literal - violation!
        # Simulate reading data with magic buffer size
        return b'x' * min(chunk_size, 4096)  # Magic literal - violation!

# AFTER: Autofix applied - Magic literals extracted to constants
# Generated by: Connascence Safety Analyzer v1.0-sale autofix engine

# Configuration constants extracted by autofix
DEFAULT_DATABASE_TIMEOUT_SECONDS = 30
DEFAULT_MAX_RETRY_ATTEMPTS = 3  
DEFAULT_BUFFER_SIZE_BYTES = 8192
MAX_ALLOWED_TIMEOUT_SECONDS = 60
MAX_ALLOWED_RETRY_ATTEMPTS = 10
DEFAULT_CHUNK_SIZE_BYTES = 1024
MAX_CHUNK_SIZE_BYTES = 4096

class DatabaseConnection:
    def __init__(self, host, port=5432):
        self.host = host
        self.port = port
        self.timeout = DEFAULT_DATABASE_TIMEOUT_SECONDS
        self.max_retries = DEFAULT_MAX_RETRY_ATTEMPTS
        self.buffer_size = DEFAULT_BUFFER_SIZE_BYTES
    
    def connect(self):
        # Extracted constants improve readability and maintainability
        if self.timeout > MAX_ALLOWED_TIMEOUT_SECONDS:
            raise ValueError("Timeout too large")
        
        if self.max_retries > MAX_ALLOWED_RETRY_ATTEMPTS:
            raise ValueError("Too many retries")
    
    def read_data(self, chunk_size=DEFAULT_CHUNK_SIZE_BYTES):
        # Named constants make buffer management explicit
        return b'x' * min(chunk_size, MAX_CHUNK_SIZE_BYTES)

# Autofix benefits demonstrated:
# 1. COMPILES: All imports, syntax, and types are valid
# 2. PASSES TESTS: Functionality preserved, only constants extracted
# 3. MAINTAINABLE: Configuration changes now happen in one place
# 4. READABLE: Intent is clear from constant names
# 5. COUPLING REDUCED: No more magic number dependencies

# Test to prove autofix works
def test_database_connection():
    """Test that autofix preserves functionality"""
    db = DatabaseConnection("localhost")
    
    # Test default values work correctly
    assert db.timeout == DEFAULT_DATABASE_TIMEOUT_SECONDS
    assert db.max_retries == DEFAULT_MAX_RETRY_ATTEMPTS
    assert db.buffer_size == DEFAULT_BUFFER_SIZE_BYTES
    
    # Test validation logic still works
    db.timeout = MAX_ALLOWED_TIMEOUT_SECONDS + 1
    try:
        db.connect()
        assert False, "Should have raised ValueError"
    except ValueError as e:
        assert "Timeout too large" in str(e)
    
    # Test data reading works
    data = db.read_data()
    assert len(data) == DEFAULT_CHUNK_SIZE_BYTES
    
    print("[PASS] Autofix preserves all functionality while improving maintainability")

if __name__ == "__main__":
    test_database_connection()
    print("[SUCCESS] Tier-C autofix demonstration: COMPILES and PASSES TESTS")