# Enterprise GitHub Actions Workflow
# Integrates Semgrep + Connascence for comprehensive coupling analysis

name: Enterprise Code Quality Analysis
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Nightly deep analysis
    - cron: '0 2 * * *'

# Environment-specific configurations for enterprise deployment
env:
  SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  CONNASCENCE_LICENSE: ${{ secrets.CONNASCENCE_ENTERPRISE_LICENSE }}
  SLACK_WEBHOOK: ${{ secrets.ARCHITECTURE_TEAM_SLACK }}
  QUALITY_GATE_THRESHOLD: "7.5"

jobs:
  # Phase 1: Fast Feedback (< 2 minutes)
  fast_analysis:
    name: Fast Coupling Detection
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for trend analysis
        
    - name: Setup Analysis Environment
      run: |
        # Install Semgrep
        python -m pip install semgrep
        
        # Install Connascence CLI (enterprise version)
        npm install -g @connascence/analyzer-enterprise
        
        # Configure enterprise settings
        mkdir -p ~/.config/connascence
        echo "${{ secrets.CONNASCENCE_CONFIG }}" > ~/.config/connascence/config.yml

    - name: Semgrep Fast Scan
      run: |
        echo "🔍 Running Semgrep coupling analysis..."
        semgrep \
          --config=data-room/artifacts/semgrep-pack/rules/ \
          --json \
          --output=semgrep-results.json \
          --exclude="node_modules/" \
          --exclude="*.test.js" \
          --exclude="*.spec.ts"
        
        echo "📊 Semgrep found $(jq '.results | length' semgrep-results.json) potential coupling issues"

    - name: Basic Connascence Metrics
      run: |
        echo "🏗️ Analyzing architectural coupling..."
        connascence-analyzer \
          --mode=fast \
          --output=json \
          --file=connascence-quick.json \
          --exclude=tests/ \
          --exclude=node_modules/ \
          src/
        
        # Extract key metrics
        COUPLING_INDEX=$(jq '.summary.coupling_index' connascence-quick.json)
        echo "COUPLING_INDEX=$COUPLING_INDEX" >> $GITHUB_ENV
        echo "📈 Current coupling index: $COUPLING_INDEX/10"

    - name: Generate PR Analysis Report
      run: |
        echo "📝 Creating combined analysis report..."
        cat > pr-analysis.md << 'EOF'
        # Code Coupling Analysis Report
        
        ## 🎯 Executive Summary
        - **Coupling Index**: $(echo $COUPLING_INDEX)/10 (Target: < ${{ env.QUALITY_GATE_THRESHOLD }})
        - **Semgrep Issues**: $(jq '.results | length' semgrep-results.json)
        - **Critical Violations**: $(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-results.json)
        - **Quality Gate**: $(if (( $(echo "$COUPLING_INDEX > ${{ env.QUALITY_GATE_THRESHOLD }}" | bc -l) )); then echo "❌ FAILED"; else echo "✅ PASSED"; fi)
        
        ## 🔍 Quick Wins Identified
        $(jq -r '.results[] | select(.extra.metadata.effort == "LOW" and .extra.metadata.impact != "LOW") | "- **" + .extra.message + "** (" + (.path // "unknown") + ":" + (.start.line // 0 | tostring) + ")"' semgrep-results.json | head -10)
        
        ## 📊 Coupling Hotspots
        $(jq -r '.hotspots[0:5][] | "- **" + .module + "**: " + (.coupling_strength | tostring) + "/10 coupling strength"' connascence-quick.json 2>/dev/null || echo "Analysis in progress...")
        
        ## 🏗️ Architectural Insights
        - **Most Coupled Module**: $(jq -r '.hotspots[0].module // "N/A"' connascence-quick.json)
        - **Recommended Focus**: $(jq -r '.recommendations[0].suggestion // "Continue monitoring coupling trends"' connascence-quick.json)
        
        ## 📈 Enterprise Impact
        - **Estimated Technical Debt**: $$(jq -r '.technical_debt.estimated_cost_usd // "Calculating..."' connascence-quick.json)
        - **Refactoring Effort**: $(jq -r '.technical_debt.estimated_hours // "TBD"' connascence-quick.json) hours
        EOF
        
        # Replace variables in the markdown
        envsubst < pr-analysis.md > pr-analysis-final.md
        mv pr-analysis-final.md pr-analysis.md

    - name: Quality Gate Check
      run: |
        echo "🚪 Checking quality gates..."
        
        # Check coupling index threshold
        if (( $(echo "$COUPLING_INDEX > ${{ env.QUALITY_GATE_THRESHOLD }}" | bc -l) )); then
          echo "❌ Quality gate failed: Coupling index $COUPLING_INDEX exceeds threshold ${{ env.QUALITY_GATE_THRESHOLD }}"
          exit 1
        fi
        
        # Check for critical Semgrep violations
        CRITICAL_COUNT=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-results.json)
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "❌ Quality gate failed: $CRITICAL_COUNT critical coupling violations found"
          exit 1
        fi
        
        echo "✅ Quality gates passed!"

    - name: Comment PR Analysis
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const analysis = fs.readFileSync('pr-analysis.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: analysis
          });

    - name: Upload Analysis Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fast-analysis-results
        path: |
          semgrep-results.json
          connascence-quick.json
          pr-analysis.md

  # Phase 2: Deep Architectural Analysis (Nightly)
  deep_analysis:
    name: Deep Architectural Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'push'
    timeout-minutes: 120
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Enterprise Analysis Environment
      run: |
        # Enhanced environment for deep analysis
        python -m pip install semgrep pandas matplotlib seaborn
        npm install -g @connascence/analyzer-enterprise @connascence/report-generator
        
        # Install additional analysis tools
        pip install git+https://github.com/connascence/architectural-debt-calculator
        
    - name: Comprehensive Semgrep Analysis  
      run: |
        echo "🔬 Running comprehensive Semgrep analysis..."
        semgrep \
          --config=data-room/artifacts/semgrep-pack/ \
          --config=p/security-audit \
          --config=p/owasp-top-ten \
          --json \
          --output=semgrep-full.json \
          --verbose \
          .
        
        echo "📊 Full analysis found $(jq '.results | length' semgrep-full.json) total issues"

    - name: Deep Connascence Analysis
      run: |
        echo "🏗️ Performing deep architectural coupling analysis..."
        connascence-analyzer \
          --mode=comprehensive \
          --output=json \
          --file=connascence-full.json \
          --include-metrics \
          --include-trends \
          --include-recommendations \
          --parallelism=4 \
          .
        
        echo "📈 Analysis complete. Generating enterprise report..."

    - name: Calculate Technical Debt
      run: |
        echo "💰 Calculating technical debt metrics..."
        architectural-debt-calculator \
          --semgrep=semgrep-full.json \
          --connascence=connascence-full.json \
          --team-size=${{ vars.TEAM_SIZE || 25 }} \
          --hourly-rate=${{ vars.DEVELOPER_HOURLY_RATE || 75 }} \
          --output=technical-debt.json

    - name: Generate Trend Analysis
      run: |
        echo "📈 Generating coupling trends..."
        python << 'EOF'
        import json
        import pandas as pd
        import matplotlib.pyplot as plt
        import seaborn as sns
        from datetime import datetime, timedelta
        
        # Load current analysis
        with open('connascence-full.json') as f:
            current_data = json.load(f)
        
        # Generate trend visualization (simulated historical data for demo)
        dates = pd.date_range(end=datetime.now(), periods=30, freq='D')
        coupling_trend = [7.8 - i*0.05 + (i%7)*0.1 for i in range(30)]
        
        plt.figure(figsize=(12, 6))
        plt.plot(dates, coupling_trend, marker='o', linewidth=2)
        plt.title('30-Day Coupling Index Trend')
        plt.ylabel('Coupling Index (0-10)')
        plt.xlabel('Date')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig('coupling-trend.png', dpi=300, bbox_inches='tight')
        
        # Generate module heatmap
        plt.figure(figsize=(10, 8))
        modules = current_data.get('modules', {})
        if modules:
            module_names = list(modules.keys())[:15]  # Top 15 modules
            coupling_values = [modules[m].get('coupling_strength', 0) for m in module_names]
            
            plt.barh(module_names, coupling_values, color='skyblue', edgecolor='navy')
            plt.title('Module Coupling Strength')
            plt.xlabel('Coupling Index')
            plt.tight_layout()
            plt.savefig('module-coupling-heatmap.png', dpi=300, bbox_inches='tight')
        EOF

    - name: Generate Executive Dashboard
      run: |
        echo "📊 Creating executive dashboard..."
        connascence-report-generator \
          --template=enterprise-executive \
          --semgrep=semgrep-full.json \
          --connascence=connascence-full.json \
          --technical-debt=technical-debt.json \
          --trends=coupling-trend.png \
          --heatmap=module-coupling-heatmap.png \
          --output=executive-dashboard.html
        
        # Generate PDF version for stakeholders
        npx playwright install chromium
        npx playwright pdf executive-dashboard.html executive-dashboard.pdf

    - name: Slack Notification for Architecture Team
      if: always()
      run: |
        COUPLING_INDEX=$(jq -r '.summary.coupling_index // "Unknown"' connascence-full.json)
        TOTAL_DEBT=$(jq -r '.total_debt_usd // "Calculating..."' technical-debt.json)
        
        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "channel": "#architecture-team",
            "username": "Coupling Analysis Bot",
            "icon_emoji": ":chart_with_upwards_trend:",
            "attachments": [{
              "color": "'$(if (( $(echo "$COUPLING_INDEX > ${{ env.QUALITY_GATE_THRESHOLD }}" | bc -l 2>/dev/null) )); then echo "danger"; else echo "good"; fi)'",
              "title": "Nightly Architecture Analysis Complete",
              "fields": [
                {"title": "Coupling Index", "value": "'"$COUPLING_INDEX"'/10", "short": true},
                {"title": "Technical Debt", "value": "$'"$TOTAL_DEBT"'", "short": true},
                {"title": "Total Issues", "value": "'"$(jq '.results | length' semgrep-full.json)"'", "short": true},
                {"title": "Quality Gate", "value": "'$(if (( $(echo "$COUPLING_INDEX > ${{ env.QUALITY_GATE_THRESHOLD }}" | bc -l 2>/dev/null) )); then echo "FAILED ❌"; else echo "PASSED ✅"; fi)'", "short": true}
              ],
              "actions": [{
                "type": "button", 
                "text": "View Dashboard",
                "url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
              }]
            }]
          }' \
          ${{ env.SLACK_WEBHOOK }}

    - name: Archive Enterprise Reports
      uses: actions/upload-artifact@v4
      with:
        name: enterprise-analysis-reports
        path: |
          semgrep-full.json
          connascence-full.json
          technical-debt.json
          executive-dashboard.html
          executive-dashboard.pdf
          coupling-trend.png
          module-coupling-heatmap.png
        retention-days: 90

    - name: Update Architecture Documentation
      if: github.event_name == 'schedule'
      run: |
        echo "📚 Updating architecture documentation..."
        
        # Update README with current metrics
        COUPLING_INDEX=$(jq -r '.summary.coupling_index' connascence-full.json)
        sed -i "s/Coupling Index: [0-9.]\+/Coupling Index: $COUPLING_INDEX/" README.md
        
        # Commit updated documentation
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "docs: Update coupling metrics to $COUPLING_INDEX [skip ci]" || exit 0
        git push

  # Phase 3: Release Quality Gate
  release_quality_gate:
    name: Release Quality Validation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [deep_analysis]
    
    steps:
    - name: Download Analysis Results
      uses: actions/download-artifact@v4
      with:
        name: enterprise-analysis-reports
        
    - name: Enterprise Quality Gate Validation
      run: |
        echo "🎯 Validating release quality gates..."
        
        COUPLING_INDEX=$(jq -r '.summary.coupling_index' connascence-full.json)
        CRITICAL_VIOLATIONS=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-full.json)
        TECHNICAL_DEBT=$(jq -r '.total_debt_usd' technical-debt.json)
        
        echo "📊 Release Quality Metrics:"
        echo "  - Coupling Index: $COUPLING_INDEX/10"
        echo "  - Critical Violations: $CRITICAL_VIOLATIONS"
        echo "  - Technical Debt: \$$TECHNICAL_DEBT"
        
        # Enterprise quality gates
        GATE_PASSED=true
        
        if (( $(echo "$COUPLING_INDEX > 8.0" | bc -l) )); then
          echo "❌ Release blocked: Coupling index too high ($COUPLING_INDEX > 8.0)"
          GATE_PASSED=false
        fi
        
        if [ "$CRITICAL_VIOLATIONS" -gt 5 ]; then
          echo "❌ Release blocked: Too many critical violations ($CRITICAL_VIOLATIONS > 5)"
          GATE_PASSED=false
        fi
        
        if [ "$GATE_PASSED" = true ]; then
          echo "✅ Release quality gates passed - deployment approved"
        else
          echo "❌ Release quality gates failed - deployment blocked"
          exit 1
        fi

    - name: Create Release Quality Report
      if: always()
      run: |
        echo "📋 Creating release quality report..."
        cat > release-quality-report.md << 'EOF'
        # Release Quality Report
        
        **Release Candidate**: `${{ github.sha }}`  
        **Analysis Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        **Quality Gate Status**: $(if [ "$GATE_PASSED" = true ]; then echo "✅ PASSED"; else echo "❌ FAILED"; fi)
        
        ## Quality Metrics
        - **Coupling Index**: $(jq -r '.summary.coupling_index' connascence-full.json)/10
        - **Total Technical Debt**: $$(jq -r '.total_debt_usd' technical-debt.json)
        - **Critical Violations**: $(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-full.json)
        - **Module Count**: $(jq '.modules | length' connascence-full.json)
        - **Average Module Coupling**: $(jq -r '.summary.average_module_coupling' connascence-full.json)
        
        ## Deployment Recommendation
        $(if [ "$GATE_PASSED" = true ]; then 
          echo "**✅ APPROVED FOR PRODUCTION DEPLOYMENT**"
          echo ""
          echo "This release meets all enterprise quality standards and is approved for production deployment."
        else 
          echo "**❌ DEPLOYMENT BLOCKED**"  
          echo ""
          echo "This release does not meet enterprise quality standards. Address the issues above before deployment."
        fi)
        EOF
        
    - name: Tag Release Quality
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "quality-approved-$(date +%Y%m%d%H%M%S)" -m "Release approved by enterprise quality gates"
        git push origin --tags