# GitLab CI Enterprise Template: Semgrep + Connascence Integration
# Professional-grade pipeline for enterprise coupling analysis

variables:
  # Enterprise configuration
  SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
  CONNASCENCE_LICENSE: $CONNASCENCE_ENTERPRISE_LICENSE
  COUPLING_THRESHOLD: "7.5"
  
  # Performance optimization
  SEMGREP_CACHE_DIR: ".semgrep-cache"
  ANALYSIS_PARALLELISM: "4"
  
  # Notification endpoints
  SLACK_WEBHOOK: $ARCHITECTURE_TEAM_SLACK
  TEAMS_WEBHOOK: $ENTERPRISE_TEAMS_WEBHOOK

# Cache configuration for performance
cache:
  key: "connascence-analysis-${CI_COMMIT_REF_SLUG}"
  paths:
    - .semgrep-cache/
    - node_modules/
    - ~/.npm/

# Pipeline stages
stages:
  - setup
  - fast-analysis  
  - comprehensive-analysis
  - quality-gates
  - reporting
  - notifications

# Stage 1: Environment Setup
setup-environment:
  stage: setup
  image: ubuntu:20.04
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip nodejs npm curl jq bc
    - python3 -m pip install semgrep pandas matplotlib
    - npm install -g @connascence/analyzer-enterprise
  script:
    - echo "🏢 Enterprise analysis environment ready"
    - semgrep --version
    - connascence-analyzer --version
    - echo "SETUP_COMPLETE=true" > setup.env
  artifacts:
    reports:
      dotenv: setup.env
    expire_in: 1 day
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

# Stage 2: Fast Analysis (< 2 minutes)
fast-coupling-analysis:
  stage: fast-analysis
  image: ubuntu:20.04
  dependencies:
    - setup-environment
  script:
    - echo "⚡ Running fast coupling analysis..."
    
    # Semgrep fast scan
    - |
      semgrep \
        --config=data-room/artifacts/semgrep-pack/rules/ \
        --json \
        --output=semgrep-fast.json \
        --exclude="node_modules/" \
        --exclude="*.test.*" \
        --exclude="test/" \
        --timeout=120 \
        .
    
    # Basic connascence metrics  
    - |
      connascence-analyzer \
        --mode=fast \
        --output=json \
        --file=connascence-fast.json \
        --parallelism=$ANALYSIS_PARALLELISM \
        --exclude=node_modules/ \
        --exclude=test/ \
        src/
    
    # Extract key metrics
    - COUPLING_INDEX=$(jq -r '.summary.coupling_index // "0"' connascence-fast.json)
    - CRITICAL_COUNT=$(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-fast.json)
    - echo "COUPLING_INDEX=$COUPLING_INDEX" > fast-metrics.env
    - echo "CRITICAL_COUNT=$CRITICAL_COUNT" >> fast-metrics.env
    - echo "📊 Fast analysis complete: $CRITICAL_COUNT critical issues, coupling index $COUPLING_INDEX"
    
  artifacts:
    paths:
      - semgrep-fast.json
      - connascence-fast.json
    reports:
      dotenv: fast-metrics.env
    expire_in: 7 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Stage 2b: Comprehensive Analysis (Scheduled/Manual)
comprehensive-analysis:
  stage: comprehensive-analysis
  image: ubuntu:20.04
  dependencies:
    - setup-environment
  timeout: 2h
  script:
    - echo "🔬 Running comprehensive architectural analysis..."
    
    # Full Semgrep analysis
    - |
      semgrep \
        --config=data-room/artifacts/semgrep-pack/ \
        --config=p/security-audit \
        --config=p/owasp-top-ten \
        --json \
        --output=semgrep-comprehensive.json \
        --exclude="node_modules/" \
        --exclude="vendor/" \
        --exclude="*.test.*" \
        --timeout=3600 \
        --verbose \
        .
    
    # Deep connascence analysis
    - |
      connascence-analyzer \
        --mode=comprehensive \
        --output=json \
        --file=connascence-comprehensive.json \
        --include-metrics \
        --include-trends \
        --include-recommendations \
        --parallelism=$ANALYSIS_PARALLELISM \
        --timeout=7200 \
        .
    
    # Technical debt calculation
    - |
      architectural-debt-calculator \
        --semgrep=semgrep-comprehensive.json \
        --connascence=connascence-comprehensive.json \
        --team-size=${TEAM_SIZE:-25} \
        --hourly-rate=${DEVELOPER_HOURLY_RATE:-75} \
        --output=technical-debt.json
    
    # Generate trend analysis
    - python3 scripts/generate-trends.py
    
    # Extract comprehensive metrics
    - COUPLING_INDEX=$(jq -r '.summary.coupling_index // "0"' connascence-comprehensive.json)
    - TOTAL_DEBT=$(jq -r '.total_debt_usd // "0"' technical-debt.json)
    - HOTSPOT_COUNT=$(jq '.hotspots | length' connascence-comprehensive.json)
    - echo "COUPLING_INDEX_COMPREHENSIVE=$COUPLING_INDEX" > comprehensive-metrics.env
    - echo "TOTAL_DEBT=$TOTAL_DEBT" >> comprehensive-metrics.env
    - echo "HOTSPOT_COUNT=$HOTSPOT_COUNT" >> comprehensive-metrics.env
    
  artifacts:
    paths:
      - semgrep-comprehensive.json
      - connascence-comprehensive.json
      - technical-debt.json
      - coupling-trends.png
      - module-heatmap.png
    reports:
      dotenv: comprehensive-metrics.env
    expire_in: 30 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - when: manual
      allow_failure: true

# Stage 3: Quality Gates
quality-gate-validation:
  stage: quality-gates
  image: alpine:latest
  dependencies:
    - fast-coupling-analysis
  before_script:
    - apk add --no-cache jq bc
  script:
    - echo "🚪 Evaluating enterprise quality gates..."
    
    # Load metrics
    - COUPLING_INDEX=${COUPLING_INDEX:-0}
    - CRITICAL_COUNT=${CRITICAL_COUNT:-0}
    
    # Enterprise quality gates
    - GATE_PASSED=true
    
    # Gate 1: Coupling Index
    - |
      if (( $(echo "$COUPLING_INDEX > $COUPLING_THRESHOLD" | bc -l 2>/dev/null || echo 0) )); then
        echo "❌ Quality gate failed: Coupling index $COUPLING_INDEX exceeds threshold $COUPLING_THRESHOLD"
        GATE_PASSED=false
      else
        echo "✅ Coupling index gate passed: $COUPLING_INDEX <= $COUPLING_THRESHOLD"
      fi
    
    # Gate 2: Critical Violations
    - |
      if [ "$CRITICAL_COUNT" -gt 5 ]; then
        echo "❌ Quality gate failed: $CRITICAL_COUNT critical violations exceed limit (5)"
        GATE_PASSED=false
      else
        echo "✅ Critical violations gate passed: $CRITICAL_COUNT <= 5"
      fi
    
    # Final gate result
    - |
      if [ "$GATE_PASSED" = true ]; then
        echo "✅ All enterprise quality gates passed!"
        echo "QUALITY_GATE_STATUS=PASSED" > quality-gate-result.env
      else
        echo "❌ Enterprise quality gates failed!"
        echo "QUALITY_GATE_STATUS=FAILED" > quality-gate-result.env
        exit 1
      fi
      
  artifacts:
    reports:
      dotenv: quality-gate-result.env
    expire_in: 7 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Stage 4: Enterprise Reporting
generate-executive-dashboard:
  stage: reporting
  image: ubuntu:20.04
  dependencies:
    - comprehensive-analysis
  before_script:
    - apt-get update && apt-get install -y nodejs npm wkhtmltopdf
    - npm install -g @connascence/dashboard-generator
  script:
    - echo "📊 Generating enterprise dashboard..."
    
    # Generate executive dashboard
    - |
      connascence-dashboard-generator \
        --template=enterprise-executive \
        --semgrep=semgrep-comprehensive.json \
        --connascence=connascence-comprehensive.json \
        --technical-debt=technical-debt.json \
        --trends=coupling-trends.png \
        --output=executive-dashboard.html \
        --theme=corporate \
        --logo="$COMPANY_LOGO_URL"
    
    # Generate PDF version
    - |
      wkhtmltopdf \
        --page-size A4 \
        --margin-top 0.75in \
        --margin-right 0.75in \
        --margin-bottom 0.75in \
        --margin-left 0.75in \
        --encoding UTF-8 \
        executive-dashboard.html \
        executive-dashboard.pdf
    
    # Create architecture team report
    - |
      cat > architecture-summary.md << EOF
      # Architecture Quality Report - Build $CI_PIPELINE_ID
      
      **Project**: $CI_PROJECT_NAME  
      **Branch**: $CI_COMMIT_REF_NAME  
      **Commit**: $CI_COMMIT_SHA  
      **Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
      
      ## Quality Metrics
      - **Coupling Index**: $(jq -r '.summary.coupling_index // "N/A"' connascence-comprehensive.json)/10
      - **Technical Debt**: \$$(jq -r '.total_debt_usd // "Calculating..."' technical-debt.json)
      - **Hotspots**: $(jq '.hotspots | length' connascence-comprehensive.json) modules need attention
      - **Critical Issues**: $(jq '[.results[] | select(.extra.severity == "ERROR")] | length' semgrep-comprehensive.json)
      
      ## Top Coupling Hotspots
      $(jq -r '.hotspots[0:5][] | "- **" + .module + "**: " + (.coupling_strength | tostring) + "/10"' connascence-comprehensive.json 2>/dev/null || echo "Analysis in progress...")
      
      ## Recommendations
      $(jq -r '.recommendations[0:3][] | "- " + .suggestion' connascence-comprehensive.json 2>/dev/null || echo "Generating recommendations...")
      
      ---
      [View Full Dashboard]($CI_PIPELINE_URL) | [Download PDF](executive-dashboard.pdf)
      EOF
    
  artifacts:
    paths:
      - executive-dashboard.html
      - executive-dashboard.pdf
      - architecture-summary.md
    expire_in: 90 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

# Stage 5: Team Notifications
notify-architecture-team:
  stage: notifications
  image: alpine:latest
  dependencies:
    - quality-gate-validation
    - comprehensive-analysis
  before_script:
    - apk add --no-cache curl jq
  script:
    - echo "📢 Sending enterprise notifications..."
    
    # Load results
    - QUALITY_STATUS=${QUALITY_GATE_STATUS:-UNKNOWN}
    - COUPLING_INDEX=${COUPLING_INDEX_COMPREHENSIVE:-${COUPLING_INDEX:-"Unknown"}}
    - TOTAL_DEBT=${TOTAL_DEBT:-"Calculating..."}
    
    # Slack notification
    - |
      if [ -n "$SLACK_WEBHOOK" ]; then
        curl -X POST -H 'Content-type: application/json' \
        --data '{
          "channel": "#architecture-team",
          "username": "GitLab Coupling Analysis",
          "icon_emoji": ":building_construction:",
          "attachments": [{
            "color": "'$(if [ "$QUALITY_STATUS" = "PASSED" ]; then echo "good"; else echo "danger"; fi)'",
            "title": "Enterprise Coupling Analysis - Pipeline '$CI_PIPELINE_ID'",
            "title_link": "'$CI_PIPELINE_URL'",
            "fields": [
              {"title": "Project", "value": "'$CI_PROJECT_NAME'", "short": true},
              {"title": "Branch", "value": "'$CI_COMMIT_REF_NAME'", "short": true},
              {"title": "Coupling Index", "value": "'"$COUPLING_INDEX"'/10", "short": true},
              {"title": "Quality Gate", "value": "'$QUALITY_STATUS'", "short": true},
              {"title": "Technical Debt", "value": "$'"$TOTAL_DEBT"'", "short": true},
              {"title": "Hotspots", "value": "'${HOTSPOT_COUNT:-"N/A"}'", "short": true}
            ],
            "actions": [{
              "type": "button",
              "text": "View Pipeline",
              "url": "'$CI_PIPELINE_URL'"
            }, {
              "type": "button", 
              "text": "Executive Dashboard",
              "url": "'$CI_PIPELINE_URL'/artifacts/file/executive-dashboard.html"
            }]
          }]
        }' \
        "$SLACK_WEBHOOK"
      fi
    
    # Microsoft Teams notification
    - |
      if [ -n "$TEAMS_WEBHOOK" ]; then
        curl -X POST -H 'Content-Type: application/json' \
        --data '{
          "@type": "MessageCard",
          "@context": "https://schema.org/extensions",
          "summary": "Enterprise Coupling Analysis Complete",
          "themeColor": "'$(if [ "$QUALITY_STATUS" = "PASSED" ]; then echo "00FF00"; else echo "FF0000"; fi)'",
          "sections": [{
            "activityTitle": "Enterprise Coupling Analysis",
            "activitySubtitle": "Pipeline '$CI_PIPELINE_ID' - '$CI_PROJECT_NAME'",
            "facts": [
              {"name": "Branch", "value": "'$CI_COMMIT_REF_NAME'"},
              {"name": "Coupling Index", "value": "'"$COUPLING_INDEX"'/10"},
              {"name": "Quality Gate", "value": "'$QUALITY_STATUS'"},
              {"name": "Technical Debt", "value": "$'"$TOTAL_DEBT"'"}
            ]
          }],
          "potentialAction": [{
            "@type": "OpenUri",
            "name": "View Pipeline",
            "targets": [{"os": "default", "uri": "'$CI_PIPELINE_URL'"}]
          }]
        }' \
        "$TEAMS_WEBHOOK"
      fi
    
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $QUALITY_GATE_STATUS == "FAILED"'

# Merge Request Analysis Comment
mr-analysis-comment:
  stage: notifications
  image: alpine:latest
  dependencies:
    - fast-coupling-analysis
    - quality-gate-validation
  before_script:
    - apk add --no-cache curl jq
  script:
    - echo "💬 Adding MR analysis comment..."
    
    # Generate MR comment
    - |
      cat > mr-comment.md << EOF
      ## 🔍 Coupling Analysis Results
      
      **Quality Gate**: $(if [ "${QUALITY_GATE_STATUS}" = "PASSED" ]; then echo "✅ PASSED"; else echo "❌ FAILED"; fi)
      
      ### Key Metrics
      - **Coupling Index**: ${COUPLING_INDEX}/10 (Target: ≤ ${COUPLING_THRESHOLD})
      - **Critical Violations**: ${CRITICAL_COUNT}
      - **Analysis Time**: $(date -u +"%H:%M:%S")
      
      ### Quick Wins Available
      $(jq -r '.results[] | select(.extra.metadata.effort == "LOW" and .extra.metadata.impact != "LOW") | "- **" + .extra.message[0:100] + "...** (" + (.path // "unknown") + ":" + (.start.line // 0 | tostring) + ")"' semgrep-fast.json | head -5)
      
      ### Enterprise Impact
      $(if [ "${QUALITY_GATE_STATUS}" = "PASSED" ]; then 
        echo "This change meets enterprise quality standards and can proceed to merge."
      else 
        echo "⚠️ This change introduces coupling issues that should be addressed before merge."
      fi)
      
      <details>
      <summary>📊 Detailed Analysis</summary>
      
      #### Coupling Categories
      $(jq -r 'group_by(.extra.metadata.category) | map({category: .[0].extra.metadata.category, count: length}) | .[] | "- " + .category + ": " + (.count | tostring) + " issues"' semgrep-fast.json | head -10)
      
      </details>
      
      *Generated by Enterprise Coupling Analysis • [View Pipeline]($CI_PIPELINE_URL)*
      EOF
    
    # Post comment using GitLab API
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ] && [ -n "$GITLAB_TOKEN" ]; then
        curl -X POST \
          -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\": $(jq -Rs . mr-comment.md)}" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"
      fi
    
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Enterprise Metrics Collection
collect-enterprise-metrics:
  stage: notifications
  image: alpine:latest
  dependencies:
    - comprehensive-analysis
  before_script:
    - apk add --no-cache curl jq
  script:
    - echo "📈 Collecting enterprise metrics..."
    
    # Extract enterprise KPIs
    - |
      jq '{
        pipeline_id: "'$CI_PIPELINE_ID'",
        project_name: "'$CI_PROJECT_NAME'",
        branch: "'$CI_COMMIT_REF_NAME'",
        commit_sha: "'$CI_COMMIT_SHA'",
        timestamp: "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
        metrics: {
          coupling_index: .summary.coupling_index,
          total_modules: (.modules | length),
          hotspot_count: (.hotspots | length),
          technical_debt_usd: .technical_debt.estimated_cost_usd,
          critical_violations: .violations.critical,
          recommendation_count: (.recommendations | length)
        }
      }' connascence-comprehensive.json > enterprise-metrics.json
    
    # Send to enterprise data warehouse (if configured)
    - |
      if [ -n "$ENTERPRISE_METRICS_ENDPOINT" ]; then
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $ENTERPRISE_METRICS_TOKEN" \
          -d @enterprise-metrics.json \
          "$ENTERPRISE_METRICS_ENDPOINT"
        echo "✅ Enterprise metrics submitted"
      else
        echo "ℹ️ Enterprise metrics collection not configured"
      fi
    
  artifacts:
    paths:
      - enterprise-metrics.json
    expire_in: 30 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  allow_failure: true